name: Rebuild

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: read 
  pages: write 
  id-token: write

jobs:
  rebuild-project:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4 

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::readxl
            any::tidyverse
            any::openxlsx
            any::googlesheets4

      - name: Import data
        run: Rscript src/data/download_data.R
        
      - name: Commit and push downloaded data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dashboard_data.xlsx
          git diff-index --quiet HEAD || git commit -m "Update data from Excel file"
          git push